Entity/Forum.php
<?php

namespace Yosimitso\WorkingForumBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Yosimitso\WorkingForumBundle\Util\Slugify;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class Forum
 *
 * @package Yosimitso\WorkingForumBundle\Entity
 *
 * @ORM\Table(name="workingforum_forum")
 * @ORM\Entity()
 */
class Forum
{
    /**
     * @var integer
     *
     * @ORM\Id
     * @ORM\Column(name="id", type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     * @Assert\NotBlank(message="forum.not_blank")
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="slug", type="string", length=255)
     */
    private $slug;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(
     *     targetEntity="Yosimitso\WorkingForumBundle\Entity\Subforum",
     *     mappedBy="forum",
     *     cascade={"persist","remove"},
     *     orphanRemoval=true
     * )
     */
    private $subForum;

    /**
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param string $name
     *
     * @return Forum
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @return ArrayCollection
     */
    public function getSubforum()
    {
        return $this->subForum;
    }

    /**
     * @param Subforum $subforum
     *
     * @return Forum
     */
    public function addSubForum(Subforum $subforum)
    {
        $this->subForum[] = $subforum;

        return $this;
    }

    /**
     * @param int $index
     *
     * @return Forum
     */
    public function removeSubForum($index)
    {
        $this->subForum->remove($index);

        return $this;
    }

    public function setSubForum(array $subforums)
    {
        $this->subForum = $subforums;

        return $this;
    }
    /**
     * Set slug
     *
     * @param string $slug
     *
     * @return Forum
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * Get slug
     *
     * @return string
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * @param string $name
     *
     * @return mixed|string
     */
    public function generateSlug($name)
    {
        $this->slug = Slugify::convert($name);

        return $this->slug;
    }

}

Entity/UserInterface.php
<?php

namespace Yosimitso\WorkingForumBundle\Entity;

/**
 * Interface UserInterface
 *
 * @package Yosimitso\WorkingForumBundle\Entity
 */
interface UserInterface
{
    public function getId();

    public function getUsername();

    public function getAvatarUrl();

    public function getNbPost();

    public function setAvatarUrl($avatar_url);

    public function setNbPost($nbPost);

    public function addNbPost($nb);
    
    public function getEmailAddress();
}

Controller/ForumController.php
<?php

namespace Yosimitso\WorkingForumBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Yosimitso\WorkingForumBundle\Controller\BaseController;
use Yosimitso\WorkingForumBundle\Entity\Forum;
use Yosimitso\WorkingForumBundle\Entity\Rules;
use Yosimitso\WorkingForumBundle\Entity\Subforum;
use Yosimitso\WorkingForumBundle\Entity\Thread;
use Yosimitso\WorkingForumBundle\Form\RulesType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

/**
 * Class ForumController
 *
 * @Route("/")
 * @package Yosimitso\WorkingForumBundle\Controller
 */
class ForumController extends BaseController
{
    private $dateFormat;
    private $postPerPage;
    private $threadPerPage;

    public function __construct(string $dateFormat, int $postPerPage, int $threadPerPage)
    {
        $this->dateFormat = $dateFormat;
        $this->postPerPage = $postPerPage;
        $this->threadPerPage = $threadPerPage;
    }

    /**
     * Display homepage of forum with subforums
     * @Route("", name="workingforum_forum")
     * @return Response
     */

    public function indexAction()
    {
        $list_forum = $this
            ->em
            ->getRepository(Forum::class)
            ->findAll();

        $this->authorizationGuard->filterForumAccess($list_forum);

        $parameters  = [ // PARAMETERS USED BY TEMPLATE
            'dateFormat' => $this->dateFormat
            ];

        return $this->render(
            '@YosimitsoWorkingForum/Forum/index.html.twig',
            [
                'list_forum' => $list_forum,
                'parameters' => $parameters
            ]
        );
    }

    /**
     * Display the thread list of a subforum
     *
     * @Route("{forum}/{subforum}/view", name="workingforum_subforum")
     * @param Request $request
     * @param int $page
     * @return Response
     */
    public function subforumAction(Forum $forum, Subforum $subforum, Request $request, $page = 1)
    {
        $list_subforum_query = $this
            ->em
            ->getRepository(Thread::class)
            ->getAllBySubforum(
                $subforum
            );

        $date_format = $this->dateFormat;

        $list_subforum = $this->paginator->paginate(
            $list_subforum_query,
            $request->query->get('page', 1)/*page number*/,
            $this->threadPerPage /*limit per page*/
        );

        $parameters  = [ // PARAMETERS USED BY TEMPLATE
            'dateFormat' => $this->dateFormat
        ];

        return $this->render(
            '@YosimitsoWorkingForum/Forum/thread_list.html.twig',
            [
                'forum' => $forum,
                'subforum' => $subforum,
                'thread_list' => $list_subforum,
                'date_format' => $date_format,
                'forbidden' => false,
                'post_per_page' => $this->postPerPage,
                'page_prefix' => 'page',
                'parameters' => $parameters
            ]
        );
    }

    /**
     * @Route("rules", name="workingforum_rules")
     * @Route("rules/{locale}", name="workingforum_rules", requirements={"locale":"\D+"})
     * @param null|string $locale
     * @return mixed
     */
    public function rulesAction($locale = null)
    {
        if (is_null($locale)) {
            $rulesList = $this->em->getRepository(Rules::class)->findAll();

            if (!empty($rulesList)) {
                $rules = $rulesList[0];
            } else {
                $rules = null;
            }
        } else {
            $rules = $this->em->getRepository(Rules::class)->findOneByLang($locale);
        }

        $form = $this->createForm(RulesType::class, null);
        
        return $this->render(
            '@YosimitsoWorkingForum/Forum/rules.html.twig',
            [
                'rules' => $rules,
                'form' => $form->createView()
            ]
        );
    }
}

Resources/views/Forum/index.html.twig
{% extends '@YosimitsoWorkingForum/Common/base.html.twig' %}
{% block forum %}
    {% include '@YosimitsoWorkingForum/Common/header.html.twig' %}
{% trans_default_domain 'YosimitsoWorkingForumBundle' %}
 <div id="wf_forum_content">
<div class="wf_breadcrumb">Forum</div>

    <div id="wf_forum">
        <p>
        {% if (is_granted("ROLE_SUPER_ADMIN") or is_granted("ROLE_ADMIN")) or is_granted("ROLE_MODERATOR") %}
            <a class="wf_button" href="{{ path('workingforum_admin') }}">{{ 'forum.admin_access' |trans }}</a>
            {% endif %}
        {% include '@YosimitsoWorkingForum/Common/search_button.html.twig' %}
         <a href="{{ path('workingforum_rules') }}" class="wf_button">{{ 'forum.forum_rules' |trans }}</a>

    </p>
{% for forum in list_forum %}
  
    <div class="wf_forum">
        <h1>{{ forum.name }}</h1>
         <table class="wf_subforum">
    {% for subforum in forum.subForum %}
       <tr>
           <td class="wf_sub_name">
               <a href="{{ path('workingforum_subforum', {'forum': subforum.forum.slug, 'subforum' : subforum.slug }) }}">{{ subforum.name }}</a>
           </td>
           <td class="wf_sub_stat">
               {{ subforum.nbThread | number_format }} {{ 'forum.nbThread' |trans }}<br />
               {{ subforum.nbPost | number_format }} {{ 'forum.nbPost' |trans }}
           </td>
           <td class="wf_sub_lastreply">
               {% if subforum.lastReplyUser is not null and subforum.lastReplyDate %}
                   {% if subforum.lastReplyUser.avatarUrl is not empty %}
                       <img class="wf_cadre-img-small wf_cadre-left hide-for-small" src="{{ asset(subforum.lastReplyUser.avatarUrl) }}">
                   {% else %}
               <img class="wf_cadre-img-small wf_cadre-left hide-for-small" src="{{ asset('bundles/yosimitsoworkingforum/images/avatar/default.png') }}">
                   {% endif %}
                   <p><strong>{{ 'forum.last_reply_date' | trans }}</strong></p>
                   <p>{{ subforum.lastReplyUser.username }}</p>
                   <p><em>{{ subforum.lastReplyDate | ago }}</em></p>
               {% endif %}
               </td>
       </tr>
        {% endfor %}
         </table>
         </div> 
    {% endfor %}

    </div>
 </div>
{% endblock %}

Resources/views/Forum/rules.html.twig
{% extends '@YosimitsoWorkingForum/Common/base.html.twig' %}
{% block forum %}
    {% include '@YosimitsoWorkingForum/Common/header.html.twig' %}
    {% trans_default_domain 'YosimitsoWorkingForumBundle' %}
    <script>
        jQuery(document).ready(function() {
            jQuery('#rules_langs').change(function(e) {
                var lang = jQuery('#rules_langs').val();
                if (typeof lang !== undefined && lang !== '') {
                    document.location.href = '{{ path('workingforum_rules' ) }}/'+lang;
                }
                return;
            });
        });
    </script>
    <div id="wf_forum_content">
        {% include '@YosimitsoWorkingForum/Common/breadcrumb.html.twig' with {'extraPath': ['forum.forum_rules' | trans] } only %}
    <div id="wf_forum">
            <div class="wf_forum wf_rules_wrapper">
                <h1>{{ 'forum.forum_rules' | trans | capitalize }}</h1>
                <div id="wf_rules">
                {% if rules is not null %}
                    <p>{{ 'admin.rules.lang' | trans | capitalize }} : {{ rules.lang }}</p>
                    <p>{{ 'forum.switch_lang' | trans }} : {{ form_widget(form.langs) }}</p>
                    <p>{{ rules.content | markdown | smiley |  raw }}</p>
                {% else %}
                    <p><em>{{ 'forum.no_rules_available' | trans }}</em></p>
                {% endif %}
                </div>
        </div>
    </div>
    </div>
{% endblock %}

Resources/views/Forum/thread_list.html.twig
{% extends '@YosimitsoWorkingForum/Common/base.html.twig' %}
{% block forum %}
    {% include '@YosimitsoWorkingForum/Common/header.html.twig' %}
    {% trans_default_domain 'YosimitsoWorkingForumBundle' %}
    {% include '@YosimitsoWorkingForum/Common/flashmsg.html.twig' %}
    <div id="wf_forum_content">
        {% if subforum is defined %}
            {% include '@YosimitsoWorkingForum/Common/breadcrumb.html.twig' with {'subforum': subforum} only %}
        {% else %}
            {% include '@YosimitsoWorkingForum/Common/breadcrumb.html.twig' with {'extraPath': [('forum.search_forum' | trans)]} only %}
        {% endif %}

        {% if forbidden is defined and forbidden %}
            <div class="wf_forum">
                <div class="wf_empty_forum">{{ forbiddenMsg | trans }}</div>
            </div>
        {% else %}

            {% if is_granted("IS_AUTHENTICATED_REMEMBERED") and subforum is defined %}
                <p>
                    <a class="wf_button wf_add"
                       href="{{ path('workingforum_new_thread', {'forum': forum.slug, 'subforum' : subforum.slug}) }}"><span
                                class="wf_add-plus"></span>{{ ('forum.new_thread' | trans) }}</a>
                </p>
            {% endif %}

            <div id="wf_forum">
                <div class="wf_forum">
                    {% if subforum is defined %}
                        <h1>{{ subforum.name }}</h1>
                    {% else %}
                        <h1>{{ 'search.results_for' | trans({'%keywords%' : keywords}) }}</h1>
                    {% endif %}

                    <table class="wf_thread_list">
                        {% if thread_list.items is not empty %}
                            {% for item in thread_list.items %}
                             {% if item.thread_slug is not empty %}
                            <tr {% if item.thread_pin %} class="wf_pin" {% elseif item.thread_resolved %} class="wf_resolved"{% endif %}>
                                <td class="wf_sub_name">
                                    <p>
                                        {% if item.thread_locked %}
                                            <img src="{{ asset('bundles/yosimitsoworkingforum/images/lock.png') }}"
                                                 width="24" style="vertical-align:bottom"/>

                                        {% endif %}
                                        {% if item.thread_pin %}
                                            <span class="wf_pinText"><img
                                                        src="{{ asset('bundles/yosimitsoworkingforum/images/pin.png') }}"
                                                        width="16"/>{#{{ 'forum.pin' | trans }} : #}</span>
                                        {% elseif item.thread_resolved %}
                                            <span class="wf_pinText"><img
                                                        src="{{ asset('bundles/yosimitsoworkingforum/images/tick.png') }}"
                                                        width="16"/>{#{{ 'forum.resolved' | trans }} : #}</span>
                                        {% endif %}

                                        <a class="wf_label"
                                           href="{{ path( 'workingforum_thread', {'forum': item.forum_slug, 'subforum' : item.subforum_slug, 'thread' : item.thread_slug}) }}">{{ item.thread_label }}</a>
                                    </p>


                                    <p class="wf_sublabel">{{ item.thread_subLabel }}</p>
                                    {% set nbPage = (item.thread_nbReplies/post_per_page) %}
                                    {% if nbPage > 1 %}
                                        <p class="wf_latest_page">
                                            <a href="{{ path( 'workingforum_thread', {'forum': item.forum_slug, 'subforum' : item.subforum_slug, 'thread' : item.thread_slug, (page_prefix) : (nbPage |round(0,'ceil')) }) }}">&rarr; {{ 'pagination.latestPage' | trans }}</a>
                                        </p>
                                    {% endif %}
                                </td>
                                <td class="wf_sub_author">
                                    <img class="wf_cadre-img-small wf_cadre-left hide-for-small" src="
                                    {% if item.author_avatarUrl is not empty %}
                                        {{ asset(item.author_avatarUrl) }}
                                    {% else %}
                                        {{ asset('bundles/yosimitsoworkingforum/images/avatar/default.png') }}
                                    {% endif %}
                                    "/>
                                    <p>{{ item.author_username |slice(0,30) }}</p>
                                    <p><em>{{ item.thread_cdate | date(parameters.dateFormat) }}</em></p>
                                </td>
                                <td class="wf_sub_stat">{{ item.thread_nbReplies }} {{ 'forum.nbPost' | trans }}</td>
                                <td class="wf_sub_lastreply">
                                    {% if item.thread_lastReplyDate is not null and item.lastReplyUser_username is not null %}
                                        {% if item.lastReplyUser_avatarUrl is not empty %}
                                            <img class="wf_cadre-img-small wf_cadre-left hide-for-small"
                                                 src="{{ asset(item.lastReplyUser_avatarUrl) }}">
                                        {% else %}
                                            <img class="wf_cadre-img-small wf_cadre-left hide-for-small"
                                                 src="{{ asset('bundles/yosimitsoworkingforum/images/avatar/default.png') }}">
                                        {% endif %}
                                        <strong>{{ 'forum.last_reply_date' | trans }}</strong><br/>
                                        {{ item.lastReplyUser_username }}
                                        <br/><em>{{ item.thread_lastReplyDate | ago }}</em>
                                    {% endif %}
                                </td>
                            {% endif %}
                            {% endfor %}
                    </table>
                {% else %}
                    </table>
                    {% if keywords is defined %}
                        <div class="wf_empty_forum">{{ 'search.no_result' | trans({'%keywords%' : keywords}) }}</div>
                    {% else %}
                        <div class="wf_empty_forum">{{ 'forum.empty_forum' | trans }}</div>
                    {% endif %}
                {% endif %}


                </div>
            </div>
            {% if thread_list is not empty %}
                {{ knp_pagination_render(thread_list) }}
            {% endif %}

        {% endif %}
    </div>
{% endblock %}